### ISSUE TITLE
[SPIKE] figure out PDF package.

### ISSUE THREAD

**Issue by PatrickDohn** [starter-code/res-gen#1]
Summary:
This is a SPIKE to investigate which PDF npm package we should use.

Acceptance criteria:
The package that is picked should be able to export a PDF document

**Comment by PatrickDohn** [comment]
Result:
We looked at these 3 packages 
http://pdfkit.org/ 
https://www.npmjs.com/package/react-pdf
https://www.npmjs.com/package/html-pdf
decided to go with http://pdfkit.org/.

**Comment by davidholyko** [comment]
upon further review, using pdfkit might be more hassle than we want.

http://pdfkit.org/demo/browser.html

This might be easier to use and is worth discussing
https://react-pdf.org/repl
