### ISSUE TITLE
[SPIKE] find a way to have customizable JSON in browser

### ISSUE THREAD

**Issue by davidholyko** [starter-code/res-gen#13]

**Comment by davidholyko** [comment]
https://json.studio/

this uses ace editor

https://www.npmjs.com/package/react-ace

**Comment by davidholyko** [comment]
https://react-pdf.org/
https://github.com/diegomura/react-pdf/tree/master/examples

**Comment by PatrickDohn** [comment]
I think this is what we need for the customizer!
https://codemirror.net/index.html
