### ISSUE TITLE
Design a user-friendly home page

### ISSUE THREAD

**Issue by davidholyko** [starter-code/res-gen#25]
https://www.pathrise.com/

https://zety.com/

**Comment by PatrickDohn** [comment]
https://resume.io/

**Comment by PatrickDohn** [comment]
https://www.resume-now.com/

**Comment by PatrickDohn** [comment]
![image](https://user-images.githubusercontent.com/44790175/101101073-be0f3900-3595-11eb-8abf-fd3cbfb18762.png)

**Comment by PatrickDohn** [comment]
Add: 
FAQ section

Navbar:
Left side will have name of product
Right side will have a Create your Resume button and a FAQ link

Hero:
Left side will have a text block
	example:
 Job-Winning Resume Templates
Instantly create your resume and get the job 2x as fast.1
    * 		Choose from our recruiter approved templates
    * 		Use pre-written text examples for your industry
    * 		Search for jobs that match your experience

	Right side will have a picture


Add: Triple column section after Hero section

Add: choose your template section

Add: footer 
	check out this project on GitHub

**Comment by PatrickDohn** [comment]
https://ethanschoonover.com/solarized/

**Comment by davidholyko** [comment]
Spike doc content moved to wiki page.

https://github.com/starter-code/res-gen/wiki/%5BSpike%5D-Home-Page-Design
