### ISSUE TITLE
Find Icons for triple column

### ISSUE THREAD

**Issue by PatrickDohn** [starter-code/res-gen#53]
**Summary**
_What is the purpose of this spike_
Find Icons to add to cards in triple column.
**Acceptance Criteria**

1. Meaningful to the content of the card it is associated with.
2.
3.

**Comment by PatrickDohn** [comment]
<img width="94" alt="Screen Shot 2020-12-18 at 6 56 25 PM" src="https://user-images.githubusercontent.com/44790175/102674308-98705b00-4163-11eb-9cfc-fa01ae88b901.png">

**Comment by PatrickDohn** [comment]
<img width="94" alt="Screen Shot 2020-12-18 at 6 58 21 PM" src="https://user-images.githubusercontent.com/44790175/102674387-d3728e80-4163-11eb-8e5b-152cdeb5f66d.png">

This one might work for the third column about getting a job.

**Comment by PatrickDohn** [comment]
<img width="93" alt="Screen Shot 2020-12-18 at 7 07 51 PM" src="https://user-images.githubusercontent.com/44790175/102674546-61e71000-4164-11eb-9b4c-fa3c2b5c3714.png">

this might work for the edit column not sure though.

**Comment by davidholyko** [comment]
Completed
